### ISSUE TITLE
Feature Request: links to folder notes on their names

### ISSUE THREAD

**Issue by Cammagno** [IdreesInc/Waypoint#1]
Now it's like this:

**Projects**
- **Celeste**
  - [[Celeste Video Script]]
  - [[Celeste]]
- [[Projects]]

According to me, it would be less messy and more efficient like this:

**[[Projects]]**
- **[[Celeste]]**
  - [[Celeste Video Script]]

Great plugin, BTW!

**Comment by IdreesInc** [comment]
That makes perfect sense, thanks for the suggestion! I'll change the format once the initial version of this plugin gets through release review.
