### ISSUE TITLE
Add Ability to Hide Waypoint Note

### ISSUE THREAD

**Issue by martydingo** [IdreesInc/Waypoint#17]
Hiya there,

I'd like to hide the note holding the Waypoint, from the list of Waypoints.

E.g. the page contains itself, as a waypoint, and I'd like to hide that.

**Comment by IdreesInc** [comment]
Hello! As of this [PR](https://github.com/IdreesInc/Waypoint/pull/10), Waypoint should now hide folder notes by default (with a setting for toggling folder note visibility). Could you do me a favor and check for plugin updates and then tell me if the problem persists? You'll need to recreate the waypoint in your notes for the update to take effect which is just a matter of deleting the old waypoint and writing the `%% Waypoint %%` flag again.

**Comment by Gewerd-Strauss** [comment]
As I understand the issue, you wanted to supress this
![grafik](https://user-images.githubusercontent.com/80548781/175492834-6341b69f-722f-476c-bc62-b75d106966a8.png)


from happening? 

If that is the case, then sadly no, version [1.1.0](https://github.com/IdreesInc/Waypoint/releases/tag/1.1.0) does not resolve the

**Comment by IdreesInc** [comment]
I understand now what you are asking for, and I agree that this would be nice. Beginning work on it now.
