### ISSUE TITLE
Add support for "outside" folder note location.

### ISSUE THREAD

**Issue by xavdid** [IdreesInc/Waypoint#19]
Maybe a duplicate of https://github.com/IdreesInc/Waypoint/issues/7, but it's a slightly different feature. It would be great to support folder notes that are outside of their folder. Eg:

```
- a/
  - b.md
  - c.md
- a.md <-- folder note
```

It's described in this help doc: https://github.com/aidenlx/alx-folder-note/wiki/folder-note-pref

**Comment by Mara-Li** [comment]
Hello ! Any update on this ? I prefer to use outside location, and Waypoint is a powerfull utils to get throught folder note and graph view ;(

**Comment by xavdid** [comment]
Thank you! Works like a charm.
