### ISSUE TITLE
Feature Request: more flexible choice of waypoints

### ISSUE THREAD

**Issue by Cammagno** [IdreesInc/Waypoint#2]
"Say your folders go from A -> B -> C. If you put a waypoint in the folder note of folder A, it'd include every file within folders A, B, and C. But if you create another waypoint in folder B, the first waypoint would only link to that folder note."

This is a great idea, but it's not so flexible.
As it is now, if I want to have a index on B, but still show all content of B in the index on A, I can't.
So, what about having two different flags, one that only generate the index (for example %% Index %%), and one that generates the index and actually marks a waypoint (for example %% Waypoint %%)?
In this way, I could put %% Waypoint %% in A and %% Index %% in B, and get what I wanted: index both in A and in B, and the index in A showing also all the content of B :)

**Comment by IdreesInc** [comment]
The more I generate new Waypoints, the more I agree that this feature would be helpful. Thanks for the suggestion!

**Comment by dawnlh** [comment]
Looking forward to the feature too! If I can see all the files including the files in the subfolders, it will be convenient to jump directly to them, rather than jump to subfolder's folder note and find it and jump again.  For more levels of subfolders, it's a disaster.

**Comment by qazero** [comment]
Any idea when the PR will be merged to master for this?
