### ISSUE TITLE
FEATURE REQUEST: Add support for code blocks instead of the current syntax

### ISSUE THREAD

**Issue by isle9** [IdreesInc/Waypoint#23]
Is there a reason why the plugin uses this weird syntax instead of using standard code blocks?

**Comment by ahmet-cetinkaya** [comment]
> Permanent and portable
Unlike other plugins, Waypoints are generated and saved as real markdown text within your folder notes. If you decide to switch to a different markdown editor that supports [[links]], all of your tables of contents will still be usable.
Note that the Waypoint plugin currently only works with Obsidian, so moving files around in another editor will cause your waypoints to be out-of-date.

https://github.com/IdreesInc/Waypoint#features

**Comment by IdreesInc** [comment]
Exactly what Ahmet said. If you are referring to the syntax to initialize a Waypoint, the double parens are used because they are considered "comments" by Obsidian and as such the flags won't be shown in the "Reader" mode.
