### ISSUE TITLE
Exclude folders/files by name or regex

### ISSUE THREAD

**Issue by eblanshey** [IdreesInc/Waypoint#37]
I use the folder "Archive" to put all archived contents, and I don't want any of the waypoints to include this directory if it is present. It'd be cool to exclude paths by regex or strings.

Thanks for the cool plugin!

**Comment by TheChilliPL** [comment]
My main uni folder note has a pretty huge waypoint thing, but half of it is my Excalidraw files 😅
They're all in subfolders with a specific name, but seems there's no way to exclude such folders yet?

**Comment by pcause** [comment]
Can you add an option to at least not index the attachments folders.

**Comment by jessycormier** [comment]
Adding to this, I have the use of 'assets' and "attachments" which may be nice to exclude from the generation.

**Comment by jstebenne** [comment]
It would be nice to be able to hide attachment folders (or any folder, a attachments folder could be named to anything the user wants)

**Comment by ToNyRANDRIAMANANTSOA** [comment]
Would it be possible to exclude a specific file for example by adding a specific property in its yaml front-matter for example ?
My issue is that some notes in the same folder have links with each other, and then the graph view become a little bit messy with the folder links from waypoint.
So what I want to achieve is that when I exclude a file for example, it won't appear in waypoint, and thus won't be linked to the folder note but only to its other related notes in the same folder.

**Comment by jessycormier** [comment]
> Would it be possible to exclude a specific file for example by adding a specific property in its yaml front-matter for example ? My issue is that some notes in the same folder have links with each other, and then the graph view become a little bit messy with the folder links from waypoint. So what I want to achieve is that when I exclude a file for example, it won't appear in waypoint, and thus won't be linked to the folder note but only to its other related notes in the same folder.

I believe there could be something added to the properties(front matter) in order to accomplish if it was implemented. 

```
---
waypoint-ignore: true`
---
```

**Comment by a13ph** [comment]
> I believe there could be something added to the properties(front matter) in order to accomplish if it was implemented.

Either this or having a field in the settings for listing exclusions.

As a temporary workaround, enabling setting `Stop Scan at Folder Notes` would allow you to ignore contents of all folders with folder notes which don't have a Waypoint

**Comment by a13ph** [comment]
Alternatively, i was told that Folder Index can ignore folders by regex:
https://github.com/turulix/obsidian-folder-index/
