### ISSUE TITLE
FR: Possibility of placing Waypoint inside Callouts?

### ISSUE THREAD

**Issue by Nightmare-Writer** [IdreesInc/Waypoint#42]
Not sure how the automatic checking of updates works with Waypoint, or if it's possible to make this a future addition. But it would be nice to be able to put Waypoints inside a Callout to make it a collapsible part of the folder note and it still detect changes made in the folder structure. Right now it can be moved inside of a callout to keep the static index but can't update for any changes made.

**Comment by GamerGirlandCo** [comment]
in the meantime, what you can do if you have the admonitions plugin, is
```
```ad-yourcalloutname
title: a title
collapse: open
%% Waypoint %%
` ` `
```

(just remove the spaces between the backticks on the last line, i don't know the right syntax to get it to render the way i want it to otherwise)
