### ISSUE TITLE
Feature Request: Option to index other file extension types

### ISSUE THREAD

**Issue by brimwats** [IdreesInc/Waypoint#5]
I would like to use waypoint in place of zootelkeeper, but I depend on Zootelkeepers' indexing of .docx, pdf, and other file formats. Could this be enabled in waypoint? Some sort of way to indicate the filetype beyond an extension (i.e. by setting emoji or icons) would be excellent as well, but more minor :)

**Comment by IdreesInc** [comment]
The filetype/emoji thing might need to wait, but adding a setting for indexing other file extensions sounds easy enough. Thanks for the suggestion!

**Comment by brimwats** [comment]
thanks @IdreesInc ! if you wanted to steal some code, zootelkeeper has code for emoji-ing certain filetypes

**Comment by ekweible** [comment]
Hi @IdreesInc, would you accept a contribution for this?

**Comment by libixi123** [comment]
I expect it a lot . That must be very great .

**Comment by LeslieP-TX** [comment]
First: Thank you so much for Waypoint! With this plugin and xpgo FolderNote I finally have the list of contents solution I've wanted.

Adding non-md files to the list would be a great help.  A few visual tweaks "while you're at it" would be much appreciated as well. 

If you could put the folders at the top of the list, and not include an extra line feed so they don't break the list, that would be great. The empty folder looks fine in Reading View, but I use Live Preview all the time these days, so it's a bit strange to see that break in the list.

My FolderNote settings:
![screenshot_20220505_104516](https://user-images.githubusercontent.com/748544/166963695-f9f57be7-8310-4195-9e94-e851bd5d4bc9.png)

File Explorer - "assets" folder contains image files only
![screenshot_20220505_104551](https://user-images.githubusercontent.com/748544/166963988-036fbd37-0c95-4443-8728-b4748ce96182.png)

Source Mode View - "assets" folder would be best at the top of the list
![screenshot_20220505_104926](https://user-images.githubusercontent.com/748544/166964100-3be4757d-107c-4d0c-b853-4a2c7629209d.png)

Reading Mode View - LOVELY, if "assets" folder was at top of list
![screenshot_20220505_104916](https://user-images.githubusercontent.com/748544/166964135-1a29ddfc-30d8-42a2-a8ca-df0eba350037.png)

Live Preview Mode, which is what I am looking at 99% of the time in Obsidian
![screenshot_20220505_104602](https://user-images.githubusercontent.com/748544/166964336-d3829867-af8a-4c56-8184-0131754f10a6.png)

**Comment by EdwardLangdon** [comment]
@IdreesInc Are there any updates to it ?

**Comment by colintedford** [comment]
Yes please to including non-Markdown files! The lack of them hurts Waypoint's usefulness in my project folders.

By default I'd like to see it follow Obsidian's File Explorer settings — always show files Obsidian can handle (images, PDFs, whatever else) and optionally show everything. Maybe you could follow the vault setting.

**Comment by IdreesInc** [comment]
Apologies for the delay on this feature, and a huge shout-out to @zhelding for making the PR to make this work!
