### ISSUE TITLE
Cannot include %%Waypoint %% in template

### ISSUE THREAD

**Issue by mineclover** [IdreesInc/Waypoint#51]
%%Waypoint %% cannot put that feature in the template because it runs automatically and generates a markdown.

**Comment by hdykokd** [comment]
I have the same problem.  I want to use it in a template.

**Comment by hdykokd** [comment]
I found a better work around using Temlater plugin

`<% "%% Waypoint %%" %> `

**Comment by IdreesInc** [comment]
I think we will have to rely on that workaround for now, since the syntax is required for the text to not show up in the editor preview

**Comment by BangJunwoo** [comment]
How about enabling ignore to be set up
%%Waypoint%% of templates are preserved when template files can be set to ignore

I prefer to be able to set to folder range

**Comment by julius-gmeinder** [comment]
@hdykokd

i just figured i could use templater and achieve what you did with

`<% "%% Waypoint %%" %>`

but this doesnt work for me and still gets replaced with the error message

`%% Error: Cannot create a waypoint in a note that's not the folder note. For more information, check the instructions [here](https://github.com/IdreesInc/Waypoint) %%`
