### ISSUE TITLE
Double percentages showing in Live Preview

### ISSUE THREAD

**Issue by securitymonster** [IdreesInc/Waypoint#79]
Hi, 

First off, thanks for this awesome plugin. I have one question though, might be an issue. I use AidenLx's Folder Note to generate and manage my Folder Notes. It has a template system where I entered the Waypoint Flag. Which looks like this:

```
# {{FOLDER_PATH}}

%% Waypoint %%
```

The issue I'm having that the table is generated correctly, but that it is enclosed like in the example below, in Live Preview mode:

```
%% Begin Waypoint %%
- [[<some note>]]
- [[<some other note>]]
%% End Waypoint %%
```
In reading mode, the tags are not showing. In source mode they obviously are. Is this by design or is there a way to hide them in Live Preview ((most of the time I am in Live Preview).

**Comment by claremacrae** [comment]
This is outside the control of any plugin, as it is just the way that comments work in Obsidian.

Reading mode hides them. Live preview shows them.

So I don't believe this is fixable.

Perhaps a CSS snippet might enable you to hide comments, but then that would likely hide _all_ comments.

**Comment by IdreesInc** [comment]
As @claremacrae helpfully mentioned, this is something that would need to be changed by the Obsidian team. Not sure what they could do though as comments are technically still text that is usually edited by the user (and as such need to be visible). I'd recommend a CSS style to make comments 50% opacity or something in the meantime and maybe mention this in the support forums if it is still bugging you!
