### ISSUE TITLE
support writing markdown links

### ISSUE THREAD

**Issue by mgamble** [IdreesInc/Waypoint#8]
One of the best aspects of Waypoint is it focus on maintaining portability by writing links to the folder note markdown file. A big step in that direction would be to have the option to write markdown links instead of wikilinks. Ideally, the plugin would use the setting described under Obsidian's "Files & Links" settings page (specifically, "New link format", "Use [[Wikilinks]]" and "Detect all file extensions" and adjust its behavior accordingly. That would afford maximum portability and allow the behavior of Waypoint to stay consistent with the rest of a user's vault. Thanks so much for writing this.

**Comment by javeoff** [comment]
+1
