### ISSUE TITLE
Waypoint plugin fails to load

### ISSUE THREAD

**Issue by ekweible** [IdreesInc/Waypoint#9]
Hello! I just installed this plugin, but it fails to load when I try to enable it. I get the following error in the console:

```
app.js:1 Plugin failure: waypoint SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at app.js:1:1444405
    at e.<anonymous> (app.js:1:1444467)
    at app.js:1:127354
    at Object.next (app.js:1:127459)
    at s (app.js:1:126198)
```

**Comment by IdreesInc** [comment]
That's odd, maybe it's conflicting with another plugin. Could you send me a list/screenshot of your plugins and the name of the platform you are using so that I can try and reproduce the error?

**Comment by ekweible** [comment]
Good call on conflicting with the plugins! I have one I'm developing locally that is symlinked into my `.obsidian/plugins/` dir and something in there must have been causing an issue (although I'm not sure why). Removing that plugin allowed me to enable Waypoint!

Out of curiosity, does this plugin also scan the `.obsidian/` directory in the vault (and does it need to)?

**Comment by ekweible** [comment]
I'm not sure what did it (maybe some other plugin updates), but it loads for me now!
