### ISSUE TITLE
Version 2.0.0 ignores 'Use WikiLinks' setting in some circumstances

### ISSUE THREAD

**Issue by claremacrae** [IdreesInc/Waypoint#91]
Hello, I think that there may have been an accidental change in 2.0.0.

I have just updated from 1.4.0 to 2.0.0, and seen some of my waypoint links change from WikiLinks to non-wikilinks.

Here is some output from version 1.4.0:

```
%% Begin Waypoint %%
- **[[Folder 2.1]]**
	- [[File in Folder 2.1]]

%% End Waypoint %%
```

This is what 2.0.0 generates for the same folder - note the link to sub-folder is no longer a WikiLink:

```
%% Begin Waypoint %%
- **[Folder 2.1](./Folder%202.1/Folder%202.1.md)**
	- [[File in Folder 2.1]]

%% End Waypoint %%
```

I attach my test vault:
[empty vault.zip](https://github.com/IdreesInc/Waypoint/files/14546226/empty.vault.zip)

Just to confirm, the settings still request WikiLinks:

<img src='https://github.com/IdreesInc/Waypoint/assets/4840096/67da22c5-9504-4e9e-9708-bc2601eb7931' width='500'>

**Comment by vburzynski** [comment]
oh, I think my code in #97 addresses this
