### ISSUE TITLE
All waypoints are "null" when nothing is in ignore regex

### ISSUE THREAD

**Issue by naturecodevoid** [IdreesInc/Waypoint#95]
1. Delete everything in ignore regex.
2. Add a waypoint.
3. Notice that it just says "null"

As a workaround, add something to the ignore regex.

**Comment by offbrands-studio** [comment]
Good find and thanks for the great tip @naturecodevoid - This has has been a bug after 2.0 drop. Cheers

**Comment by IdreesInc** [comment]
Well that's not good at all, thanks for reporting the issue! Will look into why that's happening.

**Comment by IdreesInc** [comment]
Looks like it is due to the empty box being considered a regex still and the empty regex seems to match every path. Don't know why that is, but will add logic to ignore the empty regex.
