### ISSUE TITLE
Bug? All waypoint links are markdown

### ISSUE THREAD

**Issue by bblackmoor** [IdreesInc/Waypoint#98]
Obsidian and Waypoint are both set to use wikilnks, but Waypoint does not create wikilinks. Here are my steps:

- Obsidian 1.5.11 (Windows 10 x64 Po)
- Waypoint 1.8.01 (freshly installed, all settings are default)
- No other community plugs are enabled.
- Obsidian has been exited and restarted.
- The folder "Plot" has the subfolder "The Stolen Statue".
- Both folders have a folder note ("Plot.md" and "The Stolen Statue.md", respectively).
- I enter "%% Waypoint %%" in  "Plot.md".
- "%% Waypoint %%" is replaced with:

```
%% Begin Waypoint %%
- **[The Stolen Statue](./The%20Stolen%20Statue/The%20Stolen%20Statue.md)**

%% End Waypoint %%
```

![image](https://github.com/IdreesInc/Waypoint/assets/33701300/3d8fe11d-74fb-4c9d-85f0-db0c70fd7233)

![image](https://github.com/IdreesInc/Waypoint/assets/33701300/5ec0d789-b9dc-4d5d-ad2a-4e6d3fd4f9ca)

**Comment by bblackmoor** [comment]
![image](https://github.com/IdreesInc/Waypoint/assets/33701300/3d8fe11d-74fb-4c9d-85f0-db0c70fd7233)

**Comment by bblackmoor** [comment]
![image](https://github.com/IdreesInc/Waypoint/assets/33701300/5ec0d789-b9dc-4d5d-ad2a-4e6d3fd4f9ca)

**Comment by bblackmoor** [comment]
Has no one else seen this behavior?

**Comment by IdreesInc** [comment]
Thanks for the heads up! Yeah unfortunately this bug slipped through in the last version, next version released will come with a fix from @vburzynski  that allow wikilinks to work again!
https://github.com/IdreesInc/Waypoint/pull/97
